travis:
  secure:
    BINSTAR_TOKEN: GNYRlnB29kzN6bhY2MLWX1jhVIL4h1WsmqZB6k0Jnq79bf5LQ0KxrRTE/AF8y08Gsy8LrxYkBrj90fQZw4/5ZKTT8keZCitt30Zebmvh6R9+D7iLHIfWlXHt0rKAkgYp+PiYCY56MGsqn31aOnFzGfNRWbGplptMAD7xx8lrM45jLPoWxR83g4Hb9yuLlaTbmqg8OAq14XUVcouvMb6uW7PcAtcFHZ3IJXL9qa3VrcXRu9qxUNk8+Z6ZshBq0D3rgGhcsq5kXwXP7qx2I31tbj5HjPuMtwDqOn+QAMXxi6mcZTOJcY6eaFIBECr39UYEYOydSyGS3uqoO/C4a41UAPNwT1jDCd9JzbJO9FhRd1uKagV9X2m3LMgI6kA1+IuvCp6pkRB8RWG8fsCG3yq34Y+dZ/A6OO0KhtiQO4qfjYb3adWxMa3RJI1L77K7pV2LAQeK9H/3+zpdgtr0NYIrOARD+3vmINzWvrcU1s2sFzIoeJpOIbbOJ8D0t6r6g0YKlgVAN+n/m2yEpW3jIi6D9DxxZ3b/Q9GNX0dhXDtjM35bxRtCRXFL38lSMhD20e+QoDn4JJHLO+p5gA9EFp/fuyrI9sIEgIe3whhnexm0IP5U+zg3krR+++5AKYbQ5M+qDB44qHgPm5qQN2v9VWX4xUuVApeerUPLuOchZ3g9RUY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
